
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 58
#define YY_END_OF_BUFFER 59
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[351] =
    {   0,
        1,    1,   59,   57,    1,   58,   54,   57,   55,   50,
       50,   57,   55,   50,   50,   50,   56,   50,   49,   49,
       55,   52,   51,   52,   42,   50,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   50,   50,   49,    1,   52,    0,   43,    0,
        0,    0,    0,    0,    0,    0,   51,   55,   54,    0,
        0,   53,    0,    0,   49,    0,   56,    0,   47,    0,
        7,   48,    0,    0,   50,   50,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   15,   42,   42,   42,
       42,   42,   42,   23,   42,   42,   42,   42,   42,   42,

       42,   42,   42,   42,   42,   49,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       44,    0,    0,    0,    0,    0,    0,    0,    0,    7,
        7,    7,   47,    0,    0,   49,   46,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   21,
       42,   42,   25,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   45,
       49,    0,    0,    0,    0,    0,    0,    0,    0,    6,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   47,
        0,    7,    7,    7,    0,    0,   48,    8,   42,   10,

       11,   42,   42,   42,   42,   17,   18,   42,   42,   22,
       42,   26,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   39,   42,   42,   49,    0,    0,
        3,    0,    0,    6,    6,    0,    0,    0,    0,    0,
        7,    0,   47,    9,   12,   42,   42,   42,   42,   20,
       42,   42,   42,   42,   30,   42,   42,   42,   42,   42,
       42,   37,   42,   42,   41,   49,    0,    0,    0,    0,
        0,    0,   42,   42,   16,   19,   24,   42,   42,   29,
       31,   32,   33,   34,   35,   42,   42,   42,   49,    0,
        0,    0,    0,    0,    0,   42,   14,   42,   42,   36,

       42,   42,   49,    0,    0,    4,    0,    5,    5,    0,
       13,   27,   28,   38,   40,   49,    2,    2,    0,    0,
        0,    0,    0,    0,    5,    5,    5,    5,    0,    0,
        0,   49,    2,    2,    2,    2,    2,    0,    0,    0,
        5,    0,    2,    0,    2,   49,    2,   49,   49,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   28,   28,   28,   29,   28,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   31,   30,   30,
       32,   33,   34,   35,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   30,   46,   47,   48,   49,
       50,   51,   30,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[65] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    1,    5,    6,    6,    6,
        6,    1,    1,    1,    1,    1,    1,    7,    7,    8,
        8,    1,    1,    1,    1,    8,    7,    7,    7,    7,
        7,    7,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[372] =
    {   0,
        0, 1008, 1025, 1027, 1022, 1027,  998,   60,   64,   42,
       61,  989, 1027,  996,   57,   76,   95,   62,  102,  108,
      994,  110,  994,   55,    0,  993,  120,  962,  964,  107,
       49,  101,   38,  965,   58,  964,  972,  101,  953,  962,
      955,  953,   46, 1027,  145,  987, 1027,  120, 1027,  199,
      140,  931,  120,   61,  930,  921, 1027, 1027, 1027,  960,
      253, 1027,  171,  178,  193,  209, 1027,  949,  225,  159,
      135,  256,  295,    0,  939,  938,    0,  926,  911,  263,
      869,  876,  849,  852,  839,  845,  831,  832,  829,  829,
      832,  829,  826,    0,  121,  830,  130,  827,  134,   46,

      831,  824,  125,  155,  829,  301,  149,  245,  307,  313,
      174,  249,  831,  148,  832,  819,  247,  825,  810,  822,
     1027,  319,  325,  332,  335,  344,  203,  221,  244,    0,
      276,  193,  348,  360,  364,  372,    0,    0,  811,  822,
      817,  805,  167,  819,  817,  812,  803,  809,  812,    0,
      797,  797,    0,  793,  789,  779,  777,  779,  781,  788,
      773,  771,  771,  783,  773,  751,  755,  757,  746, 1027,
      383,  389,  226,  377,  718,  720,  720,  715,  704,  751,
      711,  710,  702,  695,  706,  352,  737,  395,  399,  407,
      286,  728,  289,  418,  418,  422,  426,    0,  698,    0,

        0,  687,  695,  676,  675,    0,    0,  669,  666,    0,
      670,    0,  665,  664,  663,  659,  671,  599,  540,  542,
      540,  537,  526,  531,    0,  518,  530,  445,  521,  567,
     1027,  526,  513,    0,  562,  521,  519,  504,  521,  514,
      538,  431,  435,    0,    0,  501,  502,  507,  497,    0,
      504,  487,  495,  489,    0,  497,  492,  493,  477,  486,
      474,    0,  448,  451,    0,  459,  432,  237,  470,  418,
      418,  414,  368,  357,    0,    0,    0,  369,  366,    0,
        0,    0,    0,    0,    0,  358,  346,  327,  473,  347,
      427,  343,  258,  306,  295,  294,    0,  277,  269,    0,

      260,  211,  487,  322,  355, 1027,  524,    0,  449,  493,
        0,    0,    0,    0,    0,  506,  582,  646,  401,  534,
      706,  709,  454,  463,    0,  204,  199,  500,  499,  218,
      190,  714,    0,    0,  728,    0,  761,  718,  466,  492,
        0,  131,  125,   80,   58,  819,    0,  825,  849, 1027,
      890,  898,  901,  904,  912,  920,  923,  925,  928,  936,
      944,  952,  959,  966,  969,  972,  975,  978,  986,  994,
     1002
    } ;

static const flex_int16_t yy_def[372] =
    {   0,
      350,    1,  350,  350,  350,  350,  350,  351,  350,  350,
      350,  352,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  353,  350,  354,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  350,  350,  350,  350,  350,  351,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  355,
      356,  350,  350,  357,  350,  350,  353,  358,  358,  359,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,

      353,  353,  353,  353,  353,  350,  351,  351,  351,  351,
      351,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  355,  355,  355,  356,
      360,  356,  350,  350,  350,  350,  357,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  350,
      350,  351,  351,  350,  350,  350,  350,  350,  350,  361,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      355,  350,  360,  360,  350,  350,  350,  353,  353,  353,

      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  350,  350,  350,
      350,  350,  350,  361,  361,  350,  350,  350,  350,  350,
      356,  350,  350,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  350,  350,  350,  350,  350,
      350,  350,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  350,  350,
      350,  362,  363,  350,  350,  353,  353,  353,  353,  353,

      353,  353,  350,  364,  362,  350,  350,  365,  366,  350,
      353,  353,  353,  353,  353,  350,  350,  350,  362,  362,
      362,  362,  362,  350,  365,  367,  367,  368,  350,  369,
      370,  350,  371,  317,  318,  335,  317,  362,  362,  350,
      365,  369,  369,  370,  370,  350,  317,  350,  350,    0,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350
    } ;

static const flex_int16_t yy_nxt[1092] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       13,   14,   15,   13,   16,   17,   18,   19,   20,   20,
       20,   21,   13,   22,   23,   24,   13,   25,   25,   25,
       25,   13,    4,   13,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   25,   35,   25,   36,   25,   25,   25,
       25,   37,   38,   39,   40,   41,   42,   25,   25,   25,
       13,   43,   13,   44,   49,   51,   57,   58,   59,   62,
       57,   63,   64,   70,   65,   65,   65,   65,   71,   47,
       76,   57,  161,  345,   91,   57,   57,   92,   66,   86,
       62,   64,   50,   65,   65,   65,   65,  162,   87,   94,

       57,   67,  117,   52,   53,  345,   95,   59,   54,  118,
       68,   55,   69,   69,   69,   69,   58,   72,   56,   65,
       65,   65,   65,   72,   49,   65,   65,   65,   65,  343,
       73,   58,   74,   75,   47,  343,   73,   78,   78,   78,
       78,   51,   73,   83,   98,   99,  131,   88,   73,   89,
       84,  132,   50,   49,  100,   80,   85,  101,   90,   74,
       72,  128,  106,  106,  106,   65,  114,  152,  115,  165,
      129,  116,  155,   73,  153,   74,  159,  166,   49,   52,
       53,   50,  156,  157,   54,   73,   64,   55,   65,   65,
       65,   65,  176,  160,   56,   69,   69,   69,   69,  167,

      177,  168,   74,  107,  131,  128,   50,  107,   72,  132,
       65,   65,   65,   65,  129,  345,  108,  109,  110,  202,
      203,   73,  343,  128,   64,  107,   65,   65,   65,   65,
       49,  111,  129,   73,  325,  107,  107,  191,  291,  325,
      107,  292,   69,   69,   69,   69,  128,  107,  180,   49,
      107,  315,  107,  126,  107,  129,  112,   60,   50,  293,
      192,   60,  172,  172,  172,  126,  174,  174,  174,  174,
      122,  123,  124,  133,  133,  133,  133,   50,  128,   60,
       77,   77,   77,   77,  134,   60,  181,  194,  128,   60,
       60,  128,  130,  309,   60,  182,  134,  129,   80,  314,

      194,   60,  191,  170,   60,  130,   60,  135,   60,  135,
      125,   49,  136,  136,  136,  136,   72,   49,  171,  171,
      171,   65,  313,  304,  172,  172,  172,  121,  312,   73,
      173,  173,  173,  121,  311,  268,  186,  186,  186,   50,
      121,   73,  186,  186,  186,   50,  310,  306,  304,  187,
      187,  187,  188,  188,  188,  188,  189,  318,  189,  306,
      121,  190,  190,  190,  190,  133,  133,  133,  133,   60,
       60,   60,  196,  302,  196,  307,  195,  197,  197,  197,
      197,  136,  136,  136,  136,  170,  301,  307,  195,  136,
      136,  136,  136,   49,  107,  107,  107,  107,   72,  300,

      228,  228,  228,   65,  299,  306,  111,  111,  111,  298,
      297,   73,   60,   60,   60,   60,  190,  190,  190,  190,
      128,   50,  296,   73,  190,  190,  190,  190,  291,  194,
      242,  292,  242,  307,  241,  243,  243,  243,  243,  197,
      197,  197,  197,  197,  197,  197,  197,  170,  243,  243,
      243,  243,  243,  243,  243,  243,  295,  294,  306,  269,
       72,  170,  266,  266,  266,   65,  326,  326,  326,  326,
      306,  293,  290,   73,   72,  170,  289,  289,  289,   65,
      340,  340,  340,  340,  328,   73,  307,   73,   72,  170,
      303,  303,  303,   65,  329,  288,  287,  330,  307,   73,

      329,   73,   72,  330,  316,  316,  316,   65,  170,  319,
      319,  319,  319,   73,  286,   73,  331,  325,  325,  325,
      325,   72,  331,  332,  332,  332,   65,   73,  319,  285,
      284,  283,  319,  282,   73,  328,  281,  280,  306,  279,
      278,  320,  321,  322,  277,  276,   73,  275,  274,  273,
      319,  338,  338,  338,  241,  269,  323,  272,  271,  270,
      319,  319,  269,  235,  268,  319,  307,  231,  180,  267,
      265,  264,  319,  263,  262,  319,  261,  319,  260,  319,
      259,  324,  333,  333,  258,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  334,

      334,  334,  334,  333,  333,  333,  333,  333,  333,  334,
      334,  334,  334,  333,  333,  333,  333,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  333,  333,  333,  333,  333,  333,  257,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  335,  335,  335,  335,  333,  333,  333,
      333,  333,  333,  336,  336,  336,  336,  333,  333,  333,
      333,  337,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,

      336,  336,  336,  336,  336,  336,  333,  333,  333,  333,
      306,  256,  255,  306,  254,  253,  170,  252,  251,  250,
      249,  248,  306,  338,  338,  338,  339,  339,  339,   72,
      247,  346,  346,  346,   65,  323,  323,  323,  307,  246,
      245,  307,   73,  244,  192,  121,  240,  239,  238,  237,
      307,  236,  235,  233,   73,  335,  335,  335,  335,  232,
      231,  230,  229,  334,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  347,  347,
      347,  347,  227,  226,  225,  224,  337,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  170,  223,  222,  221,  220,  219,  170,  218,  217,
      216,  215,  214,  213,   72,  212,  348,  348,  348,   65,
       72,  211,  349,  349,  349,   65,  210,   73,  209,  208,
      207,  170,  206,   73,  205,  204,  201,  200,  199,   73,
      198,  185,  184,  183,   72,   73,   65,   65,   65,   65,
      179,  178,  175,  169,  164,  163,  158,   73,  154,  151,
      150,  149,  148,  147,  146,  145,  144,  143,  142,   73,
       48,   48,   48,   48,   48,   48,   48,   48,   60,   60,

       60,  141,   60,   60,   60,   60,   77,   77,   77,   79,
       79,   79,  127,  127,  127,  127,  140,  127,  127,  127,
      130,  130,  139,  130,  130,  130,  130,  130,  137,  137,
       78,   78,   78,  138,  138,  138,  193,  193,  193,  193,
      193,  193,  193,  193,  234,  234,   77,  234,  234,  234,
      234,  234,  305,  305,  305,  305,  305,  305,  305,  305,
      308,   77,   57,   57,   58,  308,  308,  317,  121,  120,
      119,  113,  317,  317,  325,  325,  325,  327,  327,  327,
      326,  326,  326,  341,  341,  341,  342,  342,   46,  342,
      342,  342,  342,  342,  344,  344,  105,  344,  344,  344,

      344,  344,  333,  333,  104,  333,  333,  333,  333,  333,
      103,  102,   97,   96,   93,   82,   81,   57,   47,   58,
       57,   61,   47,   46,  350,   45,    3,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350

    } ;

static const flex_int16_t yy_chk[1092] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    8,    9,   10,   10,   11,   15,
       43,   15,   15,   18,   15,   15,   15,   15,   18,   24,
       24,   15,  100,  345,   33,   11,   18,   33,   16,   31,
       16,   16,    8,   16,   16,   16,   16,  100,   31,   35,

       16,   16,   54,    9,    9,  344,   35,   43,    9,   54,
       17,    9,   17,   17,   17,   17,   22,   19,    9,   19,
       19,   19,   19,   20,   48,   20,   20,   20,   20,  343,
       19,   22,   19,   22,   22,  342,   20,   27,   27,   27,
       27,   51,   19,   30,   38,   38,   71,   32,   20,   32,
       30,   71,   48,  107,   38,   27,   30,   38,   32,   19,
       45,   70,   45,   45,   45,   45,   53,   95,   53,  103,
       70,   53,   97,   45,   95,   45,   99,  103,  111,   51,
       51,  107,   97,   97,   51,   45,   63,   51,   63,   63,
       63,   63,  114,   99,   51,   64,   64,   64,   64,  104,

      114,  104,   45,   50,  132,  127,  111,   50,   65,  132,
       65,   65,   65,   65,  127,  331,   50,   50,   50,  143,
      143,   65,  330,  128,   66,   50,   66,   66,   66,   66,
      173,   50,  128,   65,  327,   50,   50,  128,  268,  326,
       50,  268,   69,   69,   69,   69,  129,   50,  117,  108,
       50,  302,   50,   69,   50,  129,   50,   61,  173,  293,
      129,   61,  108,  108,  108,   69,  112,  112,  112,  112,
       61,   61,   61,   72,   72,   72,   72,  108,  131,   61,
       80,   80,   80,   80,   72,   61,  117,  131,  191,   61,
       61,  193,  131,  293,   61,  117,   72,  191,   80,  301,

      193,   61,  191,  106,   61,  193,   61,   73,   61,   73,
       61,  109,   73,   73,   73,   73,  106,  110,  106,  106,
      106,  106,  299,  304,  109,  109,  109,  122,  298,  106,
      110,  110,  110,  123,  296,  295,  122,  122,  122,  109,
      124,  106,  123,  123,  123,  110,  294,  292,  290,  124,
      124,  124,  125,  125,  125,  125,  126,  304,  126,  305,
      186,  126,  126,  126,  126,  133,  133,  133,  133,  186,
      186,  186,  134,  288,  134,  292,  133,  134,  134,  134,
      134,  135,  135,  135,  135,  171,  287,  305,  133,  136,
      136,  136,  136,  172,  174,  174,  174,  174,  171,  286,

      171,  171,  171,  171,  279,  319,  172,  172,  172,  278,
      274,  171,  188,  188,  188,  188,  189,  189,  189,  189,
      194,  172,  273,  171,  190,  190,  190,  190,  291,  194,
      195,  291,  195,  319,  194,  195,  195,  195,  195,  196,
      196,  196,  196,  197,  197,  197,  197,  228,  242,  242,
      242,  242,  243,  243,  243,  243,  272,  271,  323,  270,
      228,  266,  228,  228,  228,  228,  309,  309,  309,  309,
      339,  269,  267,  228,  266,  289,  266,  266,  266,  266,
      324,  324,  324,  324,  309,  228,  323,  266,  289,  303,
      289,  289,  289,  289,  310,  264,  263,  310,  339,  266,

      329,  289,  303,  329,  303,  303,  303,  303,  316,  340,
      340,  340,  340,  289,  261,  303,  310,  328,  328,  328,
      328,  316,  329,  316,  316,  316,  316,  303,  307,  260,
      259,  258,  307,  257,  316,  328,  256,  254,  320,  253,
      252,  307,  307,  307,  251,  249,  316,  248,  247,  246,
      307,  320,  320,  320,  241,  240,  307,  239,  238,  237,
      307,  307,  236,  235,  233,  307,  320,  232,  230,  229,
      227,  226,  307,  224,  223,  307,  222,  307,  221,  307,
      220,  307,  317,  317,  219,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,

      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  318,  318,  218,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,

      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      321,  217,  216,  322,  215,  214,  332,  213,  211,  209,
      208,  205,  338,  321,  321,  321,  322,  322,  322,  332,
      204,  332,  332,  332,  332,  338,  338,  338,  321,  203,
      202,  322,  332,  199,  192,  187,  185,  184,  183,  182,
      338,  181,  180,  179,  332,  335,  335,  335,  335,  178,
      177,  176,  175,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  337,  337,
      337,  337,  169,  168,  167,  166,  337,  337,  337,  337,

      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  346,  165,  164,  163,  162,  161,  348,  160,  159,
      158,  157,  156,  155,  346,  154,  346,  346,  346,  346,
      348,  152,  348,  348,  348,  348,  151,  346,  149,  148,
      147,  349,  146,  348,  145,  144,  142,  141,  140,  346,
      139,  120,  119,  118,  349,  348,  349,  349,  349,  349,
      116,  115,  113,  105,  102,  101,   98,  349,   96,   93,
       92,   91,   90,   89,   88,   87,   86,   85,   84,  349,
      351,  351,  351,  351,  351,  351,  351,  351,  352,  352,

      352,   83,  352,  352,  352,  352,  353,  353,  353,  354,
      354,  354,  355,  355,  355,  355,   82,  355,  355,  355,
      356,  356,   81,  356,  356,  356,  356,  356,  357,  357,
      358,  358,  358,  359,  359,  359,  360,  360,  360,  360,
      360,  360,  360,  360,  361,  361,   79,  361,  361,  361,
      361,  361,  362,  362,  362,  362,  362,  362,  362,  362,
      363,   78,   76,   75,   68,  363,  363,  364,   60,   56,
       55,   52,  364,  364,  365,  365,  365,  366,  366,  366,
      367,  367,  367,  368,  368,  368,  369,  369,   46,  369,
      369,  369,  369,  369,  370,  370,   42,  370,  370,  370,

      370,  370,  371,  371,   41,  371,  371,  371,  371,  371,
       40,   39,   37,   36,   34,   29,   28,   26,   23,   21,
       14,   12,    7,    5,    3,    2,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "flex_source.l"
#line 2 "flex_source.l"
typedef enum {
    KEYWORD,
    IDENTIFIER,
    LITERAL,
    OPERATOR,
    PUNTUACTOR,
    COMMENT,
    LEXICALERROR,
	PREPROCESSOR
} TOKEN;
#line 815 "lex.yy.c"
/* Cualquier caracter en blanco (tabs, salto linea, espacios)*/
/* si le mando s es white espace?*/
#line 22 "flex_source.l"
	/* CONSTANTES */
/* Acepta hileras que pueden no tener numeros antes del punto decimal y que deben tener un numero despues del punto decimal. El e^n es opcional */
/* EJEMPLO:  -.2e+3  ,  +.4E12  ,  .3e-4  ,  -3.3e-4  ,   .56  */
/* Acepta hileras que deben tener un numero antes del punto decimal y que pueden pueden no traer un numero despues del punto decimal. El e^n es opcional */
/* EJEMPLO:  -3.e3  ,  +-22.32 ,  2.e+33  ,  0.e-1  ,  4.  */
/* Constante real sin el punto decimal */
/* EJEMPLO:  -77e-3  ,  +-22e-3   ,  20  ,  -10  ,  3E3  ,   302E2   */
/* Numeros en base 8. Comienzan con 0 seguido de numeros entre 1-7. Longitud de 12 */
/* Base 16: Comienzan con 0x o 0X seguido de uno o mas numeros del 0-9 o de a-f */
/* Secuencia de letras, digitos, y underscores. Primer caracter no puede ser digito. Puede nombrarse "_" solamente. */
/* Caracteres especiales: Secuencias de escape (digitos octales y hexadecimales) */
/* Caracter Simple: 'C' */
/* Cadena de caracteres: "Secuencia de caracteres" */
	/* Comments */
	/* funciona enviandole desde consola todo el archivo \/+\*((\**[^\/])|(\**(\n)\/*))*\*\/+    */ 
	/* para pruebas \/*\*(.)*\*\/+ */
/* Comentario normal: // No admite line breaks */
/* Arithmetic Operators */
/* Assignment Operators */
/* Comparison Operators */
/* Increment and decrement operators */
/* Logical operators */
/* PUNTUACTOR OPERATORS */
/* Member access operators */
#line 843 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 81 "flex_source.l"

	/* Caracteres Blancos printf("WHITESPACE \"%s\"\n", yytext); */
	
#line 1067 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 351 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1027 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 84 "flex_source.l"
/* Ignora espacios en blanco */
	YY_BREAK
/* DIRECTIVAS DEL PREPROCESADOR */
case 2:
YY_RULE_SETUP
#line 87 "flex_source.l"
return PREPROCESSOR;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 88 "flex_source.l"
return PREPROCESSOR;
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 89 "flex_source.l"
return PREPROCESSOR;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 90 "flex_source.l"
return PREPROCESSOR;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 91 "flex_source.l"
return PREPROCESSOR;
	YY_BREAK
/* Comentarios */
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 94 "flex_source.l"
return COMMENT;
	YY_BREAK
/* KEYWORDS */
case 8:
YY_RULE_SETUP
#line 97 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 98 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 99 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 100 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 101 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 102 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 103 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 104 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 105 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 106 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 107 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 108 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 109 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 110 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 111 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 112 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 113 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 114 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 115 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 116 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 117 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 118 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 119 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 120 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 121 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 122 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 123 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 124 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 125 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 126 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 127 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 128 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 129 "flex_source.l"
return KEYWORD;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 130 "flex_source.l"
return KEYWORD;
	YY_BREAK
/* Identificadores: PD: se valida despues de las palabras reservadas */
case 42:
YY_RULE_SETUP
#line 133 "flex_source.l"
return IDENTIFIER;
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 135 "flex_source.l"
return LITERAL;
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 136 "flex_source.l"
return LITERAL;
	YY_BREAK
/* OCTAL */
case 45:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 139 "flex_source.l"
return LITERAL;
	YY_BREAK
/* HEXADECIMAL */
case 46:
YY_RULE_SETUP
#line 142 "flex_source.l"
return LITERAL;
	YY_BREAK
/* Numeros reales */
case 47:
YY_RULE_SETUP
#line 145 "flex_source.l"
return LITERAL;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 146 "flex_source.l"
return LITERAL;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 147 "flex_source.l"
return LITERAL;
	YY_BREAK
/* Operadores del lenguaje */
case 50:
YY_RULE_SETUP
#line 150 "flex_source.l"
return OPERATOR;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 151 "flex_source.l"
return OPERATOR;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 152 "flex_source.l"
return OPERATOR;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 153 "flex_source.l"
return OPERATOR;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 154 "flex_source.l"
return OPERATOR;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 155 "flex_source.l"
return PUNTUACTOR;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 156 "flex_source.l"
return OPERATOR;
	YY_BREAK
/* ERRORES LEXICOS */
case 57:
YY_RULE_SETUP
#line 159 "flex_source.l"
return LEXICALERROR;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 161 "flex_source.l"
return EOF;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 163 "flex_source.l"
ECHO;
	YY_BREAK
#line 1435 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 351 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 351 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 350);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 163 "flex_source.l"


/**
 * When yylex is finished, it call function yywrap(). If yywrap() returns 1, then yylex returns 0 to its caller. That means "end of file".
 * If yywrap returns 0, then yylex assumes that you have stored a different file into yyin, and it starts reading that file.
 */
int yywrap() {
    return 1; 
}

